version: "3.8"
services:
  ansible:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ansible
    container_name: ansible
    hostname: ansible
    tty: true
    restart: always
    volumes:
      - ansible:/opt/ansible
    working_dir: /opt/ansible
    networks:
      - default
volumes:
  ansible:
    driver: local
  serverspec:
    driver: local
networks:
  default:
    name: ansible_network
