version: "3.8"
services:
  # ansible実行環境
  ansible:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ansible
    container_name: ansible
    hostname: ansible
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /ansible
    working_dir: /ansible
